retargeting:
  type: DexPilot
  urdf_path: ../liberhand_description/urdf/liberhand_left.urdf

  # Target refers to the retargeting target, which is the robot hand
  wrist_link_name: "hand_left_wrist"
  finger_tip_link_names: [ "hand_left_f54_end", "hand_left_f14_end", "hand_left_f24_end", "hand_left_f34_end", "hand_left_f44_end" ]
  scaling_factor: 1.2

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2